[package]
name = "janken-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libui = { git = "https://github.com/tasuren/libui.git", version = "0.2.0" }
native-windows-gui = "1.0.13"
